<Project Sdk="Lombiq.MSBuild.OrchardCore.Tests.Sdk/2.1.0">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update=".htmlvalidate.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lombiq.Tests.UI" Version="$(PackageVersionLombiqTestsUI)" />
    <PackageReference Include="Lombiq.Analyzers.OrchardCore" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DotNest.Core.SDK.Web\DotNest.Core.SDK.Web.csproj" />
  </ItemGroup>
</Project>
