name: Build and Test

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    name: Build and Test
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-dotnet.yml@dev
    with:
      timeout-minutes: 5

  spelling:
    name: Spelling
    uses: Lombiq/GitHub-Actions/.github/workflows/spelling.yml@dev
    with:
      dictionary-source-prefixes: >
        {
          "lombiq": "https://raw.githubusercontent.com/Lombiq/GitHub-Actions/dev/.github/actions/spelling/",
          "cspell": "https://raw.githubusercontent.com/check-spelling/cspell-dicts/v20220816/dictionaries/"
        }
      extra-dictionaries: |
        cspell:aws/aws.txt
        cspell:csharp/csharp.txt
        cspell:css/css.txt
        cspell:django/django.txt
        cspell:dotnet/dotnet.txt
        cspell:filetypes/filetypes.txt
        cspell:html/html.txt
        cspell:npm/npm.txt
        cspell:rust/rust.txt
        cspell:scala/scala.txt
        cspell:software-terms/src/software-terms.txt
        cspell:typescript/typescript.txt
        lombiq:allow.txt
        lombiq:expect.txt
        lombiq:liquid.txt
        lombiq:patterns.txt
