name: Build

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  call-build-workflow:
    name: Build
    uses: Lombiq/GitHub-Actions/.github/workflows/build-dotnet.yml@dev
    with:
      timeout-minutes: 5

  spelling:
    name: Spelling
    uses: Lombiq/GitHub-Actions/.github/workflows/spelling.yml@dev
