name: Build

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  call-build-workflow:
    name: Build
    uses: Lombiq/GitHub-Actions/.github/workflows/build-dotnet.yml@dev
    with:
      # This should be windows-latest but keeping on Ubuntu until we start working on
      # https://lombiq.atlassian.net/browse/NEST-316 since Ubuntu is faster and cheaper per minute.
      machine-types: "[\"ubuntu-latest\"]"
      timeout-minutes: 60
