name: Build and Test

on:
  pull_request:
  push:
    branches:
      - dev-piedone

jobs:
  build-and-test:
    name: Build and Test
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      timeout-minutes: 5
      dotnet-consolidation-exclude-version-regex: '\-alpha'

  spelling:
    name: Spelling
    uses: Lombiq/GitHub-Actions/.github/workflows/spelling.yml@dev
    with:
      additional-dictionaries: |
        lombiq-lgha:dictionaries/Liquid.txt
        cspell:html/dict/html.txt
