name: Renovate

on:
  # Run manually.
  workflow_dispatch:
  # Run on the 5th of every month.
  schedule:
    - cron: 0 4 5 * *
  # Run on pushes to dev when the Renovate configuration changes.
  push:
    branches:
      - dev
    paths:
      - renovate.json5

jobs:
  renovate:
    name: Renovate
    uses: Lombiq/GitHub-Actions/.github/workflows/renovate.yml@dev
    secrets:
      CHECKOUT_TOKEN: ${{ secrets.LOMBIQBOT_GITHUB_PERSONAL_ACCESS_TOKEN }}
